Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ThienASPMVC08032023.Models;
using ThienASPMVC08032023.Repository.InterfaceRepo;

namespace ThienASPMVC08032023.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    [Route("/{Controller}/{Action=Index}/{id?}")]
    public class CategoryController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        public CategoryController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }


        // GET: CategoryController
        public async Task<ActionResult> Index()
        {
            var categories = await _repo.CategoryRepo.GetAllCategoriesAsync();
            return View(categories);
        }

        // GET: CategoryController/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var category = await _repo.CategoryRepo.GetCategoryByIdAsync(id);
            if (category == null) { return NotFound($"Not found category has id = {id}"); }
            return View(category);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id, Name, Description")] Category categoryVM)
        {
            if (!ModelState.IsValid) { return BadRequest(ModelState); }
            _repo.CategoryRepo.CreateCategory(categoryVM);
            await _repo.SaveAsync();
            return RedirectToAction("Index");
        }

        // GET: CategoryController/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var category = await _repo.CategoryRepo.GetCategoryByIdAsync(id);
            if (category == null) { return NotFound($"Not found category has id = {id}"); }
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id, Name, Description")] Category categoryVM)
        {
            if (id != categoryVM.Id) { return NotFound($"wrong id, {id} != {categoryVM.Id}"); }
            if (!ModelState.IsValid) { return BadRequest(ModelState); }
            _repo.CategoryRepo.UpdateCategory(categoryVM);
            await _repo.SaveAsync();
            return RedirectToAction("Index");
        }

        //GET: CategoryController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var category = await _repo.CategoryRepo.GetCategoryByIdAsync(id);
            if (category == null) { return NotFound($"Not found category has id = {id}"); }
            return View(category);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            var category = await _repo.CategoryRepo.GetCategoryByIdAsync(id);
            _repo.CategoryRepo.DeleteCategory(category);
            await _repo.SaveAsync();
            return RedirectToAction("Index");
        
        }
    }
}

Areas/Admin/Controllers/ClipsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using ThienASPMVC08032023.Models;
using ThienASPMVC08032023.Repository.InterfaceRepo;
using X.PagedList;

namespace ThienASPMVC08032023.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    [Route("/{controller}/{action=Index}/{id:int?}")]
    public class ClipsController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        private readonly ILogger<ClipsController> _logger;
        private readonly UserManager<AppUser> _userManager;

        [TempData]
        public string? StatusMessage { get; set; }

        public ClipsController(IRepositoryWrapper repo, ILogger<ClipsController> logger, UserManager<AppUser> userManager)
        {
            _repo = repo;
            _logger = logger;
            _userManager = userManager;
        }

        // GET: Clips
        [HttpGet]
        public async Task<ActionResult> Index(string searchString,string sortBy, int? currentPage, int? pageSize)
        {
            var qrClips = await _repo.ClipRepo.GetAllClipsAsync(searchString, sortBy);

            ViewData["SortByName"] = sortBy == "name" ? "name_desc" : "name";
            ViewData["SortByTimeCreated"] = sortBy == "timeCreated" ? "timeCreated_desc" : "timeCreated";

            // paging
            if (currentPage == null)
            {
                currentPage = 1;
            }
            if (pageSize == null)
            {
                pageSize = 5;
            }
            return View(qrClips.ToPagedList((int)currentPage, (int)pageSize));
        }

        // GET: Clips/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var clip = await _repo.ClipRepo.GetClipByIdAsync(id);
            if (clip == null) { return NotFound($"Not Found Clip has id ={id}"); }
            return View(clip);
        }

        // GET: Clips/Create
        public async Task<ActionResult> Create()
        {
            var categories = await _repo.CategoryRepo.GetAllCategoriesAsync();
            ViewBag.listCategories = new SelectList(categories, "Id", "Name");
            return View();
        }
      
        // POST: Clips/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Name,Description,Url,CategoryId")] Clip clipVM)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                clipVM.AuthorUser = currentUser;
                _repo.ClipRepo.CreateClip (clipVM);
                await _repo.SaveAsync();
                StatusMessage = $"Uploaded clip Name :  {clipVM.Name} Successfully!";
            }
            return RedirectToAction("Index");
        }

        // GET: Clips/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var categories = await _repo.CategoryRepo.GetAllCategoriesAsync();
            ViewBag.listCategories = new SelectList(categories, "Id", "Name");
            var clip = await _repo.ClipRepo.GetClipByIdAsync(id);
            if (clip == null) { return NotFound($"Not Found Clip has id ={id}"); }
            return View(clip);
        }

        // POST: Clips/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id,[Bind("Id,Name,Description,Url,CategoryId")] Clip clipVM)
        {
            if(id != clipVM.Id) { return NotFound($"wrong id, {id} != {clipVM.Id}"); }
            if (ModelState.IsValid)
            {
                var newClip = await _repo.ClipRepo.GetClipByIdAsync(id);
                newClip.Name = clipVM.Name;
                newClip.Description = clipVM.Description;
                newClip.Url = clipVM.Url;
                newClip.CategoryId = clipVM.CategoryId;
                _repo.ClipRepo.UpdateClip(newClip);
                await _repo.SaveAsync();
                StatusMessage = $"Edited Clip name : {clipVM.Name} Successfully!";
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Clips/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var clip =await _repo.ClipRepo.GetClipByIdAsync(id);
            if (clip == null) { return NotFound($"Not Found Clip has id ={id}"); }
            return View(clip);
        }

        // POST: Clips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var clip = await _repo.ClipRepo.GetClipByIdAsync(id);
            _repo.ClipRepo.DeleteClip(clip);
            await _repo.SaveAsync();
            StatusMessage = $"Deleted clip successfully!";
            return RedirectToAction(nameof(Index));
        }

    }
}

Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ThienASPMVC08032023.Database;
using ThienASPMVC08032023.Models;

namespace ThienASPMVC08032023.Areas.Admin.Controllers
{
    [Authorize(Roles ="admin")]
    [Area("Admin")]
    [Route("/Role/{action=Index}")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly ILogger<RoleController> _logger;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager, ILogger<RoleController> logger)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _logger = logger;
        }

        [TempData]
        public string? StatusMessage { get; set; }


        // GET: RoleController
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        // GET: RoleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Name")] IdentityRole role )
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return NotFound();  
                }

                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    StatusMessage = $"Created a role named : {role.Name} successfully ";

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: RoleController/Delete/5
        public async Task<ActionResult> Delete(string roleid)
        {
            if (string.IsNullOrEmpty(roleid))
            {
                return NotFound("Not Found roleid");
            }
            var role = await _roleManager.FindByIdAsync(roleid);
            if (role == null)
            {
                return NotFound("not found role");
            }
            return View(role);
        }

        // POST: RoleController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string roleid)
        {
            try
            {
                if (string.IsNullOrEmpty(roleid))
                {
                    return NotFound("not found roleid");
                }

                var role = await _roleManager.FindByIdAsync(roleid);
                if (role == null) 
                { 
                    return NotFound("role not found"); 
                }
                
                var deleteResult = await _roleManager.DeleteAsync(role);
                if (deleteResult.Succeeded)
                {
                    StatusMessage = $"Deleted role named : {role.Name} successfully ";
                }
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ThienASPMVC08032023.Areas.Admin.Models.User;
using ThienASPMVC08032023.Models;
using X.PagedList;

namespace ThienASPMVC08032023.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    [Area("Admin")]
    [Route("/User/{Action=Index}")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager; 
        private readonly ILogger<UserController> _logger;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(RoleManager<IdentityRole> roleManager,UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, ILogger<UserController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _roleManager = roleManager;
        }

        [TempData]
        public string? StatusMessage { get; set; }



        // GET: UserController
        public ActionResult Index(int? currentPage, int? pageSize)
        {
            List<AppUser> users = _userManager.Users.ToList();

            if (currentPage == null)
            {
                currentPage = 1;
            }
             
            if (pageSize == null)
            {
                pageSize = 10;
            }

            
                
            return View(users.ToPagedList((int)currentPage, (int)pageSize));
        }

        // GET: UserController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        // GET: UserController/SetRoleUser
        public async Task<ActionResult> SetRoleUser(string userId)
        {
            var SetRoleUserModel = new SetRoleUserModel();



            if (string.IsNullOrEmpty(userId))
            {
                return NotFound(" not found userId ");
            }
            SetRoleUserModel.User = await _userManager.FindByIdAsync(userId);

            SetRoleUserModel.RolesUser = await _userManager.GetRolesAsync(SetRoleUserModel.User);
            
            List<IdentityRole> roles = _roleManager.Roles.ToList();
            IEnumerable<string> allRolesName = roles.Select(r => r.Name).ToList();

            ViewBag.allRolesName = new SelectList(allRolesName);
            return View(SetRoleUserModel);
        }


        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetRoleUser(string userId, [Bind("RolesUser,User")]SetRoleUserModel SetRoleUserModel)
        {
            try
            {
                List<IdentityRole> roles = _roleManager.Roles.ToList();
                IEnumerable<string> allRolesName = roles.Select(roles => roles.Name);

                ViewBag.allRolesName = new SelectList(allRolesName);


                if (string.IsNullOrEmpty(userId))
                {
                    return NotFound("not found userId");
                }

                SetRoleUserModel.User = await _userManager.FindByIdAsync(userId);
                if (SetRoleUserModel.User == null)
                {
                    return NotFound($"not found user, id = {userId}");
                }

                IList<string> currentRolesUser = await _userManager.GetRolesAsync(SetRoleUserModel.User);

                IEnumerable<string> deleteRolesUser = currentRolesUser.Where(role => !SetRoleUserModel.RolesUser!.Contains(role));

                IEnumerable<string> AddRolesUser = SetRoleUserModel.RolesUser!.Where(role => !currentRolesUser.Contains(role));

                var resultDeleteRolesUser = await _userManager.RemoveFromRolesAsync(SetRoleUserModel.User, deleteRolesUser);

                if (!resultDeleteRolesUser.Succeeded)
                {
                    return NotFound("Delete Roles Fail");
                }

                var resultAddRolesUser = await _userManager.AddToRolesAsync(SetRoleUserModel.User, AddRolesUser);

                if (!resultAddRolesUser.Succeeded)
                {
                    return NotFound("Add Roles Fail");

                }

                StatusMessage = $" Added roles for user: {SetRoleUserModel.User.UserName}";

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        public async Task<ActionResult> Delete(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return NotFound("Not found userId");
            }

            var user = await _userManager.FindByIdAsync(userId);   

            if (user == null)
            {
                return NotFound("not found user");
            }

            return View(user);
        }

        // POST: UserController/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string userId)
        {
            try
            {
                if (string.IsNullOrEmpty(userId))
                {
                    return NotFound("Not Found userId");
                }

                var user = await _userManager.FindByIdAsync(userId);

                if (user == null)
                {
                    return NotFound("Not Found User");
                }

                var deleteResult = await _userManager.DeleteAsync(user);

                if (deleteResult.Succeeded)
                {
                    StatusMessage = $"Deleted user : {user.UserName} successfully!";

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThienASPMVC08032023</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    @* 
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThienASPMVC08032023.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand text-warning" asp-area="" asp-controller="Home" asp-action="Index">GAMING CLIP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        
                        @if (User.IsInRole("admin") || User.IsInRole("manager"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Manager</a>
                                <div class="dropdown-menu ">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category Manager</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Clips" asp-action="Index">Clips Manager</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Role" asp-action="Index">Roles Manager</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users Manager</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item ">
                            <a class="nav-link btn btn-outline-success" asp-area="" asp-controller="Home" asp-action="Upload">Upload</a>
                        </li>

                    </ul>
                    <form class="d-flex" asp-controller="Home" asp-action="Index" method="get">
                        <input name="searchString" class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>

                    <partial name="_LoginPartial">

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GAMING CLIP
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MainCommentPartial.cshtml
@using ThienASPMVC08032023.ViewModel;
@model CommentViewModel

@{

}

<div class="card-footer py-3 border-0">
    <form asp-controller = "Comment" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <input asp-for="ClipId" type="hidden" class="form-control" />
        <input asp-for="MainCommentId" type="hidden" class="form-control" />


        <div class="form-outline w-100">
            <label asp-for="CommentMsg" class="control-label"></label>
            <input asp-for="CommentMsg" class="form-control" />
            <span asp-validation-for="CommentMsg" class="text-danger"></span>
        </div>

        <div class ="float-end mt-2 pt-1">
            <input type="submit" value="Comment" class="btn btn-primary" />
        </div>
    </form>
</div>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!string.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}